---
title: "day_4_training"
author: "Sistla"
date: "January 17, 2019"
output: html_document
---
```{r}
 library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
```

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## data training chpt 13. Download data from website.

```{r}
esc <-read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method = "libcurl"), stringsAsFactors = FALSE)

head(esc)
 
```

Calculate annial, regional total escapement
*separate the date into year - month - day
*group_by, summarize to calclate the sum over unique region-year species cominations
*filter for salmon species

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(year = as.numeric(year)) %>% 
  group_by(SASAP.Region, Species, year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Pink", "Chum", "Coho"))

head(annual_esc)
```
Look at datatable (DT library)

```{r}
datatable(annual_esc)
```


#static plots

```{r}
ggplot(data = annual_esc, mapping = aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col() 
```

```{r}
#create object for theme
my_theme <-   theme_bw()+
  theme_minimal()

ggplot(data = filter(annual_esc, SASAP.Region == "Kodiak"),
       aes(x = year, y = escapement, color = Species)) +
  geom_line()+
geom_point()+
  ylab("escapement (# of fish)")+
  ggtitle("Kodiak salmon escapement")+
  my_theme
 
      
```


```{r}
ggplot(annual_esc, aes(x = year, y = escapement, color = Species))+
  geom_line()+
  geom_point()+
  facet_wrap(~SASAP.Region, scales = "free_y")+
  my_theme
```


```{r, fig.height = 10, fig.width = 8}
p <- ggplot(annual_esc, aes(x = year, y = escapement, color = Species))+
  geom_line()+
  geom_point()+
  facet_wrap(~SASAP.Region, scales = "free", ncol = 2)+
  my_theme

p
ggsave("region_escapement.png", plot = p, height = 10, width = 8, units = "in")


```


```{r}
write.csv(annual_esc, "annual_escapement.csv",
          row.names = F)
```

```{r}
locations <- esc  %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

datatable(locations)
```


Create leaflet map

```{r}
leaflet(locations) %>% 
  addTiles() %>%  ## adds map background based on long/lat information
  addMarkers(~Longitude, ~Latitude, popup = ~Location)

```

